"""initial_schema

Revision ID: f858b6a15ba7
Revises: 
Create Date: 2026-05-06 15:40:47.256592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f858b6a15ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'employee'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key('fk_projects_manager_id_users', 'projects', 'users', ['manager_id'], ['id'])
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('active', 'idle', 'unproductive'), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('window_title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('app_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_rules_id'), 'app_rules', ['id'], unique=False)
    op.create_table('app_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('productive', 'unproductive', 'prohibited', 'neutral'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_usages_date'), 'app_usages', ['date'], unique=False)
    op.create_index(op.f('ix_app_usages_id'), 'app_usages', ['id'], unique=False)
    op.create_index(op.f('ix_app_usages_user_id'), 'app_usages', ['user_id'], unique=False)
    op.create_table('idle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_logs_id'), 'idle_logs', ['id'], unique=False)
    op.create_index(op.f('ix_idle_logs_user_id'), 'idle_logs', ['user_id'], unique=False)
    op.create_table('productivity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('productive_pct', sa.Integer(), nullable=True),
    sa.Column('idle_pct', sa.Integer(), nullable=True),
    sa.Column('unproductive_pct', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_scores_date'), 'productivity_scores', ['date'], unique=False)
    op.create_index(op.f('ix_productivity_scores_id'), 'productivity_scores', ['id'], unique=False)
    op.create_index(op.f('ix_productivity_scores_user_id'), 'productivity_scores', ['user_id'], unique=False)
    op.create_table('url_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.Enum('productive', 'unproductive', 'prohibited', 'neutral'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_usages_date'), 'url_usages', ['date'], unique=False)
    op.create_index(op.f('ix_url_usages_id'), 'url_usages', ['id'], unique=False)
    op.create_index(op.f('ix_url_usages_user_id'), 'url_usages', ['user_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_id'), 'screenshots', ['id'], unique=False)
    op.create_index(op.f('ix_screenshots_user_id'), 'screenshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_user_id'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_url_usages_user_id'), table_name='url_usages')
    op.drop_index(op.f('ix_url_usages_id'), table_name='url_usages')
    op.drop_index(op.f('ix_url_usages_date'), table_name='url_usages')
    op.drop_table('url_usages')
    op.drop_index(op.f('ix_productivity_scores_user_id'), table_name='productivity_scores')
    op.drop_index(op.f('ix_productivity_scores_id'), table_name='productivity_scores')
    op.drop_index(op.f('ix_productivity_scores_date'), table_name='productivity_scores')
    op.drop_table('productivity_scores')
    op.drop_index(op.f('ix_idle_logs_user_id'), table_name='idle_logs')
    op.drop_index(op.f('ix_idle_logs_id'), table_name='idle_logs')
    op.drop_table('idle_logs')
    op.drop_index(op.f('ix_app_usages_user_id'), table_name='app_usages')
    op.drop_index(op.f('ix_app_usages_id'), table_name='app_usages')
    op.drop_index(op.f('ix_app_usages_date'), table_name='app_usages')
    op.drop_table('app_usages')
    op.drop_index(op.f('ix_app_rules_id'), table_name='app_rules')
    op.drop_table('app_rules')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint('fk_projects_manager_id_users', 'projects', type_='foreignkey')
    op.drop_table('users')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
